words = [
    "addrs",
    "backend's",
    "clippy",
    "dtolnay",
    "fdfind",
    "lossy",
    "raii",
    "rustfmt",
    "swatinem",
    "tokio",
    "xzf",
]
ignore_paths = ["Cargo.lock"]
ignore_patterns = ['\b[a-fA-F0-9]{64}\b']
