name: CI

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch: {}

jobs:
  format-check:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
        with: { persist-credentials: false }
      - uses: dtolnay/rust-toolchain@nightly
        with: { components: rustfmt }
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all --check

  lint:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
        with: { persist-credentials: false }
      - uses: dtolnay/rust-toolchain@1.95.0
        with: { components: clippy }
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --workspace --all-targets

  spell-check:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
        with: { persist-credentials: false }
      - run: |
          sudo apt-get update
          sudo apt-get install -y fd-find
          curl -L https://github.com/blopker/codebook/releases/download/v0.3.39/codebook-lsp-aarch64-unknown-linux-musl.tar.gz | tar -xz
          ./codebook-lsp lint $(fdfind --hidden --exclude .git --type file)

  test:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
        with: { persist-credentials: false }
      - uses: dtolnay/rust-toolchain@1.95.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --workspace --all-targets

  all-checks:
    runs-on: ubuntu-24.04-arm
    needs: [format-check, lint, spell-check, test]
    steps:
      - run: echo "All checks passed!"
